{{- if .Values.ingress.enabled -}}
{{- $fullName := include "quarkus.fullname" . -}}-service
{{- $svcPort := .Values.service.port -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "quarkus.fullname" . }}-service
  labels:
    {{- include "quarkus.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
     {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.ingress.className }}
  ingressClassName: {{ .Values.ingress.className }}
  {{- end }}
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "quarkus.fullname" . }}-service
                port:
                  number: 8080

{{- end }}