apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "quarkus.fullname" . }}-cm
  labels:
    {{ include "quarkus.labels" . | nindent 4 }}
data:
  quarkus.mongodb.connection-string: "{{ .Values.backend.datasource.uri }}"
  quarkus.mongodb.database: "{{ .Values.backend.datasource.name }}"